language: minimal

services:
  - docker

env:
  global:
    IMAGE_NAME=wiotp/grafana4iot

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t ${IMAGE_NAME}:$TRAVIS_BRANCH .
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker tag ${IMAGE_NAME}:$TRAVIS_BRANCH ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}:latest
      else
        docker push ${IMAGE_NAME}:$TRAVIS_BRANCH
      fi
    fi
