version: '2'

services:
  grafana:
    image: wiotp/grafana4iot
    build: github.com/ibm-watson-iot/grafana4iot.git
    volumes:
      - "/mnt/whisper:/opt/graphite/storage/whisper"
      - "/mnt/grafana:/opt/grafana/data"
    ports: 
      - "80:80"
    mem_limit: 512M
    restart: always
  
  connector:
    image: wiotp/connector-statsd
    build: github.com/ibm-watson-iot/connector-statsd.git
    links:
      - grafana:graphite
    environment:
      - GRAPHITE_HOST=graphite
      - GRAPHITE_PORT=2003
      - WIOTP_API_KEY=${WIOTP_API_KEY}
      - WIOTP_API_TOKEN=${WIOTP_API_TOKEN}
    mem_limit: 256M
    restart: always
